"""The operations behind the MCP tools: one function per verb, each doing exactly one thing.

The tools in `kanban_mcp.tools` route to these (the Idea Space ones are registered as tools one to one).
"""

from .projects import list_projects, create_project, update_project
from .members import list_members, add_member, remove_member
from .tickets import (
    list_tickets,
    create_ticket,
    get_ticket,
    get_ticket_workspace_path,
    update_ticket_status,
    update_ticket,
    create_child_ticket,
    delete_ticket,
    DEFAULT_ACTIVITY_ENTRIES,
)
from .relations import block_ticket, unblock_ticket, link_tickets, unlink_tickets
from .comments import (
    add_comment,
    update_comment,
    delete_comment,
    restore_comment,
    list_comments,
)
from .work_log import add_work_log, update_work_log, delete_work_log
from .test_cases import add_test_case, update_test_case, delete_test_case
from .branches import add_branch, update_branch, delete_branch, checkout_branch
from .checklists import (
    add_acceptance_criterion,
    toggle_acceptance_criterion,
    delete_acceptance_criterion,
    add_sub_task,
    toggle_sub_task,
    delete_sub_task,
)
from .docs import (
    list_docs_pages,
    get_docs_page,
    create_docs_page,
    update_docs_page,
    move_docs_page,
    duplicate_docs_page,
    delete_docs_page,
    restore_docs_page,
    list_docs_recycle_bin,
    list_docs_versions,
    get_docs_version,
    restore_docs_version,
    resolve_docs_links,
    search_docs,
    import_docs,
    link_ticket_doc,
    unlink_ticket_doc,
)
from .ideas import (
    list_idea_tickets,
    create_idea_ticket,
    get_idea_ticket,
    update_idea_ticket,
    delete_idea_ticket,
    update_idea_status,
    promote_idea_to_ticket,
    add_assumption,
    update_assumption_status,
    delete_assumption,
    add_microthought,
    delete_microthought,
    get_idea_activity_trail,
)

__all__ = [
    "list_projects",
    "create_project",
    "update_project",
    "list_members",
    "add_member",
    "remove_member",
    "list_tickets",
    "create_ticket",
    "get_ticket",
    "get_ticket_workspace_path",
    "update_ticket_status",
    "update_ticket",
    "create_child_ticket",
    "delete_ticket",
    "DEFAULT_ACTIVITY_ENTRIES",
    "block_ticket",
    "unblock_ticket",
    "link_tickets",
    "unlink_tickets",
    "add_comment",
    "update_comment",
    "delete_comment",
    "restore_comment",
    "list_comments",
    "add_work_log",
    "update_work_log",
    "delete_work_log",
    "add_test_case",
    "update_test_case",
    "delete_test_case",
    "add_branch",
    "update_branch",
    "delete_branch",
    "checkout_branch",
    "add_acceptance_criterion",
    "toggle_acceptance_criterion",
    "delete_acceptance_criterion",
    "add_sub_task",
    "toggle_sub_task",
    "delete_sub_task",
    "list_docs_pages",
    "get_docs_page",
    "create_docs_page",
    "update_docs_page",
    "move_docs_page",
    "duplicate_docs_page",
    "delete_docs_page",
    "restore_docs_page",
    "list_docs_recycle_bin",
    "list_docs_versions",
    "get_docs_version",
    "restore_docs_version",
    "resolve_docs_links",
    "search_docs",
    "import_docs",
    "link_ticket_doc",
    "unlink_ticket_doc",
    "list_idea_tickets",
    "create_idea_ticket",
    "get_idea_ticket",
    "update_idea_ticket",
    "delete_idea_ticket",
    "update_idea_status",
    "promote_idea_to_ticket",
    "add_assumption",
    "update_assumption_status",
    "delete_assumption",
    "add_microthought",
    "delete_microthought",
    "get_idea_activity_trail",
]
